export const CREATE_NEW_DON_HANG ="CREATE_NEW_DON_HANG";
export const WATCHER_CHI_TIET_DON_HANG ='WATCHER_CHI_TIET_DON_HANG';
export const REDUCER_CHI_TIET_DON_HANG ='REDUCER_CHI_TIET_DON_HANG';
export const REDUCER_DONG_DON_HANG ='REDUCER_DONG_DON_HANG';
export const REDUCER_DON_HANG = 'REDUCER_DON_HANG';