export const CREATE_NEW_SAN_PHAM="CREATE_NEW_SAN_PHAM";
export const CREATE_NEW_SAN_PHAM_REDUCER="CREATE_NEW_SAN_PHAM_REDUCER";
export const TANG_SO_LUONG_SAN_PHAM ="TANG_SO_LUONG_SAN_PHAM";
export const GIAM_SO_LUONG_SAN_PHAM ="GIAM_SO_LUONG_SAN_PHAM";
export const UPDATE_DATA_INPUT ="UPDATE_DATA_INPUT";