
export const WATCHER_ADD_TO_CART ='WATCHER_ADD_TO_CART';
export const REDUCER_ADD_TO_CART = 'REDUCER_ADD_TO_CART';
export const WATCHER_CLEAR_MY_CART = 'WATCHER_CLEAR_MY_CART';
export const REDUCER_CLEAR_MY_CART = 'REDUCER_CLEAR_MY_CART';